auth_enabled: false # For development; enable multi-tenancy in production

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

common:
  instance_addr: loki
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://mimir:9093

analytics:
  reporting_enabled: false

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_parallelism: 32
  # Production-grade limits
  ingestion_rate_mb: 100 # MB per second per tenant
  ingestion_burst_size_mb: 200 # Burst size in MB
  max_line_size: 256KB # Maximum log line size
  max_streams_per_user: 10000 # Maximum streams per tenant
  max_global_streams_per_user: 10000
  retention_period: 168h # 7 days retention
