# Grafana Mimir configuration for single-node deployment
target: all

multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks

compactor:
  data_dir: /data/compactor

distributor:
  ring:
    instance_addr: mimir
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: mimir
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/ruler

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

store_gateway:
  sharding_ring:
    replication_factor: 1

memberlist:
  bind_port: 7946
  join_members:
    - mimir:7946

limits:
  max_global_series_per_user: 1500000
  max_global_series_per_metric: 20000
  ingestion_rate: 10000
  ingestion_burst_size: 200000

runtime_config:
  file: ""