version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Singapore"
    rebase-strategy: "auto"
    open-pull-requests-limit: 0  # Disabled - using Renovate for PRs
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Singapore"
    rebase-strategy: "auto"
    open-pull-requests-limit: 0  # Disabled - using Renovate for PRs

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Asia/Singapore"
    rebase-strategy: "auto"
    open-pull-requests-limit: 0  # Disabled - using Renovate for PRs

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Asia/Singapore"
    rebase-strategy: "auto"
    open-pull-requests-limit: 0  # Disabled - using Renovate for PRs

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "Asia/Singapore"
    rebase-strategy: "auto"
    open-pull-requests-limit: 0  # Disabled - using Renovate for PRs
