# This is the base Air configuration for running Go services
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  poll = true
[log]
  time = true
