name: "Mask Azure Secrets"
description: "Comprehensive masking of Azure globally unique identifiers to prevent leaks in public repositories"
author: "Coruscant Platform Team"

inputs:
  tenant-id:
    description: "Entra tenant ID"
    required: true
  subscription-id-foundation:
    description: "Foundation subscription ID"
    required: true
  tfstate-storage-account-name:
    description: "Terraform state storage account name"
    required: true
  subscription-id-mapping-json:
    description: "JSON mapping of subscription IDs"
    required: true
  storage-account-prefix:
    description: "Storage Account name prefix for pattern-based masking"
    required: true
  sp-gha-tf-apply-platform-obj-id:
    description: "ID of the service principal used by GitHub Actions for applying platform"
    required: false
  sp-gha-tf-apply-landingzone-obj-id:
    description: "ID of the service principal used by GitHub Actions for applying landing zones"
    required: false

runs:
  using: "composite"
  steps:
    - name: Mask Azure secrets
      shell: bash
      run: |
        set -euo pipefail

        # Mask individual secret values
        echo "::add-mask::${{ inputs.tenant-id }}"
        echo "::add-mask::${{ inputs.subscription-id-foundation }}"
        echo "::add-mask::${{ inputs.tfstate-storage-account-name }}"
        echo "::add-mask::${{ inputs.sp-gha-tf-apply-platform-obj-id }}"
        echo "::add-mask::${{ inputs.sp-gha-tf-apply-landingzone-obj-id }}"

        # Mask storage account prefix (used to construct account names)
        PREFIX="${{ inputs.storage-account-prefix }}"
        echo "::add-mask::${PREFIX}"

        # Extract and mask each subscription ID from JSON mapping
        echo '${{ inputs.subscription-id-mapping-json }}' | jq -r '.[]' | while read -r id; do
          echo "::add-mask::${id}"
        done

        # Function to mask Azure resource with all common DNS patterns
        mask_azure_resource() {
          local name="$1"
          echo "::add-mask::${name}"

          # Storage Account endpoints (all services)
          echo "::add-mask::${name}.blob.core.windows.net"
          echo "::add-mask::${name}.dfs.core.windows.net"
          echo "::add-mask::${name}.file.core.windows.net"
          echo "::add-mask::${name}.queue.core.windows.net"
          echo "::add-mask::${name}.table.core.windows.net"
          echo "::add-mask::${name}.z23.web.core.windows.net"
          echo "::add-mask::https://${name}.blob.core.windows.net/"
          echo "::add-mask::https://${name}.dfs.core.windows.net/"
          echo "::add-mask::https://${name}.file.core.windows.net/"
          echo "::add-mask::https://${name}.queue.core.windows.net/"
          echo "::add-mask::https://${name}.table.core.windows.net/"
          echo "::add-mask::https://${name}.z23.web.core.windows.net/"

          # Container Registry
          echo "::add-mask::${name}.azurecr.io"
          echo "::add-mask::https://${name}.azurecr.io/"

          # Key Vault
          echo "::add-mask::${name}.vault.azure.net"
          echo "::add-mask::https://${name}.vault.azure.net/"

          # App Service / Azure Functions
          echo "::add-mask::${name}.azurewebsites.net"
          echo "::add-mask::https://${name}.azurewebsites.net/"

          # API Management
          echo "::add-mask::${name}.azure-api.net"
          echo "::add-mask::https://${name}.azure-api.net/"

          # Cosmos DB
          echo "::add-mask::${name}.documents.azure.com"
          echo "::add-mask::https://${name}.documents.azure.com/"

          # Azure SQL Server
          echo "::add-mask::${name}.database.windows.net"

          # Redis Cache
          echo "::add-mask::${name}.redis.cache.windows.net"

          # Service Bus / Event Hubs Namespace
          echo "::add-mask::${name}.servicebus.windows.net"
          echo "::add-mask::https://${name}.servicebus.windows.net/"

          # SignalR Service
          echo "::add-mask::${name}.service.signalr.net"
          echo "::add-mask::https://${name}.service.signalr.net/"

          # Static Web Apps
          echo "::add-mask::${name}.azurestaticapps.net"
          echo "::add-mask::https://${name}.azurestaticapps.net/"

          # Azure Front Door
          echo "::add-mask::${name}.azurefd.net"
          echo "::add-mask::https://${name}.azurefd.net/"

          # Azure CDN
          echo "::add-mask::${name}.azureedge.net"
          echo "::add-mask::https://${name}.azureedge.net/"

          # Cognitive Services
          echo "::add-mask::${name}.cognitiveservices.azure.com"
          echo "::add-mask::https://${name}.cognitiveservices.azure.com/"

          # Azure Machine Learning
          echo "::add-mask::${name}.api.azureml.ms"
          echo "::add-mask::https://${name}.api.azureml.ms/"
        }

        # Scan Terraform files for storage account resources and mask their names
        # This finds azurerm_storage_account resources and extracts computed names

        if [[ -d "azure/tf" ]]; then
          # Find storage account name attributes in .tf files
          # Matches: name = "..." or name = "${var.storage_account_prefix}..."
          STORAGE_NAMES=$(grep -rh '^\s*name\s*=' azure/tf/ --include="*.tf" 2>/dev/null | \
            grep -E 'storage_account|blob|dfs|file|queue|table' | \
            sed -n 's/.*name\s*=\s*"\([^"]*\)".*/\1/p' | \
            sort -u || true)

          # Replace variable references with actual prefix value
          while IFS= read -r name_pattern; do
            [[ -z "$name_pattern" ]] && continue

            # Substitute the prefix variable
            actual_name="${name_pattern//\$\{var.storage_account_prefix\}/${PREFIX}}"

            # If it still contains variables, try to evaluate common ones
            if [[ "$actual_name" =~ \$\{ ]]; then
              # Extract other variables and try common values
              # For each.value patterns, generate common region/zone combinations
              if [[ "$actual_name" =~ each\.value ]]; then
                # Common Azure regions (short codes)
                for region in we ne ue ae se ce no ea sa; do
                  test_name="${actual_name//\$\{each.value.short_name\}/${region}}"
                  # Only mask if it's a valid storage account name format
                  if [[ "$test_name" =~ ^[a-z0-9]{3,24}$ ]]; then
                    mask_azure_resource "${test_name}"
                  fi
                done
              fi
            else
              # Name doesn't contain variables, mask directly
              if [[ "$actual_name" =~ ^[a-z0-9]{3,24}$ ]]; then
                mask_azure_resource "${actual_name}"
              fi
            fi
          done <<< "$STORAGE_NAMES"
        fi

        # Always mask the tfstate storage account (known from secret)
        mask_azure_resource "${{ inputs.tfstate-storage-account-name }}"

        echo "✓ Azure secrets masking complete"
