name: "Trivy"
description: "Run Trivy scan, always upload SARIF, fail job if findings exist"

inputs:
  scan-type:
    description: "Scan type: fs (SCA), config (IaC), image (Container Image)"
    required: true
  image:
    description: "Image reference (required if scan-type=image)"
    required: false
  category:
    description: "Optional category to distinguish multiple SARIF uploads for the same tool"
    required: false
  working-directory:
    description: "Optional working directory for the scan (default: repo root)"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Run Trivy (Debug Output)
      if: inputs.scan-type != 'image'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "=== DEBUG: Trivy scan results (table format) ==="
        trivy ${{ inputs.scan-type }} ${{ inputs.scan-type == 'image' && inputs.image || '.' }} || true
        echo "=== END DEBUG OUTPUT ==="
      continue-on-error: true

    - name: Run Trivy
      id: trivy
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
      with:
        scan-type: ${{ inputs.scan-type }}
        image-ref: ${{ inputs.image }}
        scan-ref: ${{ inputs.scan-type == 'image' && inputs.image || inputs.working-directory }}
        format: sarif
        output: trivy.sarif
        exit-code: 0
      continue-on-error: true

    - name: Rename SARIF tool name
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f trivy.sarif ]; then
          echo "No trivy.sarif file found, creating empty SARIF"
          # Create minimal valid SARIF with no results
          cat > trivy.sarif << 'EOF'
        {
          "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
          "version": "2.1.0",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "Trivy",
                  "version": "0.65.0"
                }
              },
              "results": []
            }
          ]
        }
        EOF
        fi
        
        case "${{ inputs.scan-type }}" in
          fs) tool="Trivy-SCA" ;;
          config) tool="Trivy-IaC" ;;
          image) tool="Trivy-Image" ;;
          *) tool="Trivy" ;;
        esac
        echo "Using tool name: $tool"
        jq --arg tn "$tool" '.runs[].tool.driver.name=$tn' trivy.sarif > renamed.sarif
        echo "SARIF ready for upload"

    - name: Upload SARIF to GitHub
      if: always()
      uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3.30.3
      with:
        sarif_file: ${{ inputs.working-directory }}/renamed.sarif
        category: ${{ inputs.category }}
