name: "Cleanup Old Docker Images"

on:
  schedule:
    - cron: "0 3 * * 0" # Runs every Sunday at 3am UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  list-packages:
    name: "List Container Packages"
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: "Get list of container packages"
        id: get-packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          packages=$(gh pkg list --package-type container --json name -q '.[] | .name' | jq -c 'map(.)')
          echo "packages=$packages" >> $GITHUB_OUTPUT

  cleanup-images:
    name: "Cleanup ${{ matrix.package }} Docker Image"
    needs: list-packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        package: ${{ fromJson(needs.list-packages.outputs.packages) }}
    steps:
      - name: "Delete old package versions"
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 #v5.0.0
        with:
          package-name: ${{ matrix.package }}
          package-type: "container"
          min-versions-to-keep: 2
          token: ${{ secrets.GITHUB_TOKEN }}
