name: "SonarQube Scan"

on:
  push:
    branches: [ "main", ]
  pull_request:
    branches: [ "main", ]
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sundays at midnight

permissions:
  contents: read

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-dir: [
          ".",
          "shared/golib",
          "systems/kyber",
        ]
        token-secret: [
          SONAR_TOKEN_ROOT,
          SONAR_TOKEN_GOLIB,
          SONAR_TOKEN_KYBER,
        ]
      fail-fast: false          # keep scanning others if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 #v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets[matrix.token-secret] }}
        with:
          projectBaseDir: ${{ matrix.project-dir }}
